import Head from 'next/head'
import {AWelcome,BText,CFor,DFeatures,EBenefist,FText,GOptions,HFeedBack,IText,JComments,KSubscribe} from '../components/ZIndex'

export default function Home() {
  return (
  <>
      <Head>
        <title>Startup Landing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AWelcome/>
      <BText/>
      <CFor/>
      <DFeatures/>
      <EBenefist/>
      <FText/>
      <GOptions/>
      <HFeedBack/>
      <IText/>
      <JComments/>
      <KSubscribe/>


  



   </>
  )
 
}
