import Head from 'next/head'
import Navmenu from '../components/Navmenu'
import Header1 from '../components/Header1'
export default function Home() {


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <Navmenu/>
    <Header1/>

  
    
     
    </>
  )
}
